name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: package
        run: |-
            echo $(pwd)
            ls -al
            cd pingpong && ./mvnw clean package -Dmaven.test.skip=true  

    - name: Upload jar
        uses: actions/upload-artifact@v1
        with:
          name: jar
          path: pingpong/target

    - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Download jar
        uses: actions/download-artifact@v1
        with: 
          name: jar
          path: pingpong/target

    - name: Build and push   
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ping-pong-app"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          tags: lnsth/pingpong:${{ github.sha }}


      


      

      